app_recrutamento/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('', include ('home.urls')),
    path('candidaturas/', include('candidaturas.urls')),
    path('empresa/', include('relatorios.urls')),
    
]

candidaturas/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('listar_vagas_candidato/', views.listar_vagas_candidato, name='listar_vagas_candidato'),
    path('candidatar_vaga/<int:id>', views.candidatar_vaga, name='candidatar_vaga'),
    path('visualizar_candidaturas/<int:id>/', views.visualizar_candidaturas, name='visualizar_candidaturas'),
    path('logout/', views.custom_logout, name='logout')
]

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
   path('auth/', include('usuarios.urls')),
   path('', views.home, name='home'),
   path('vagas/', include('vagas.urls'))
]

candidaturas/models.py
from django.db import models
from django.contrib.auth.models import User
from vagas.models import Vaga
# Create your models here.

class Candidatura(models.Model):
    candidato = models.ForeignKey(User, on_delete=models.CASCADE)
    vaga = models.ForeignKey(Vaga, on_delete=models.CASCADE)
    pretensao_salarial = models.DecimalField(max_digits=10, decimal_places=2)
    experiencia = models.TextField()
    escolaridade = models.CharField(max_length=20, choices=[
        ('fundamental', 'Ensino fundamental'),
        ('medio', 'Ensino médio'),
        ('tecnologo', 'Tecnólogo'),
        ('superior', 'Ensino Superior'),
        ('pos', 'Pós / MBA / Mestrado'),
        ('doutorado', 'Doutorado'),
    ])
    data_candidatura = models.DateTimeField(auto_now_add=True)

    def calcular_pontuacao(self):
        pontos = 0
        escolaridades = ['fundamental','medio','tecnologo','superior','pos','doutorado']
        vaga_min_salario, vaga_max_salario = map(float, self.vaga.faixa_salarial.split('-'))

        if self.pretensao_salarial >= vaga_min_salario and self.pretensao_salarial <= vaga_max_salario :
            pontos +=1

        if escolaridades.index(self.escolaridade) >= escolaridades.index(self.vaga.escolaridade_minima):
            pontos +=1

        print(vaga_max_salario, vaga_min_salario, self.pretensao_salarial)

        return pontos
        
    def __str__(self):
        return f"{self.candidato.username} - {self.vaga.nome}"

vagas/models.py
from django.db import models

# vagas/models.py

class Vaga(models.Model):
    FAIXA_SALARIAL_CHOICES = [
        ('0-1000', 'Até 1.000'),
        ('1000-2000', 'De 1.000 a 2.000'),
        ('2000-3000', 'De 2.000 a 3.000'),
        ('3000-100000', 'Acima de 3.000'),
    ]

    ESCOLARIDADE_CHOICES = [
        ('fundamental', 'Ensino fundamental'),
        ('medio', 'Ensino médio'),
        ('tecnologo', 'Tecnólogo'),
        ('superior', 'Ensino Superior'),
        ('pos', 'Pós / MBA / Mestrado'),
        ('doutorado', 'Doutorado'),
    ]
    nome = models.CharField(max_length=200, verbose_name='Nome da vaga')
    requisitos = models.TextField(verbose_name='Requisitos')
    faixa_salarial = models.CharField(max_length=15,choices=FAIXA_SALARIAL_CHOICES, verbose_name='Faixa salarial')
    escolaridade_minima = models.CharField(max_length=20, choices=ESCOLARIDADE_CHOICES, verbose_name='Escolaridade mínima')
    status = models.CharField(default='ativo',max_length=10)
    criado_em = models.DateTimeField(auto_now_add=True)
    modificado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
         return self.nome

  

candidaturas/forms.py
from django import forms
from .models import Candidatura

class CandidaturaForm(forms.ModelForm):
    class Meta:
        model = Candidatura
        fields = ['pretensao_salarial','experiencia','escolaridade']
        
       

candidaturas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Candidatura
from .forms import CandidaturaForm
from vagas.models import Vaga
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from usuarios.decorators import empresa_required



@login_required
def listar_vagas_candidato(request):
    vagas = Vaga.objects.filter(status='ativo')
    return render (request, 'listar_vagas_candidato.html', {'vagas':vagas})

@login_required
def candidatar_vaga(request,id):
    vaga = get_object_or_404(Vaga, id=id)
    if Candidatura.objects.filter(candidato=request.user, vaga=vaga).exists():
        messages.warning(request, 'Você já se candidatou para essa vaga.')
        return redirect('listar_vagas_candidato')
    
    if request.method == 'POST':
        form = CandidaturaForm(request.POST)
        if form.is_valid():
            candidatura = form.save(commit=False)
            candidatura.candidato = request.user
            candidatura.vaga = vaga
            candidatura.save()
            return redirect ('listar_vagas_candidato')
    else:
        form = CandidaturaForm()
        return render (request,'candidatar_vaga.html', {'form':form, 'vaga':vaga})

@empresa_required
@login_required
def visualizar_candidaturas(request, id):
    vaga = get_object_or_404(Vaga, id=id)
    candidaturas = Candidatura.objects.filter(vaga = vaga).select_related('candidato')
    return render(request, 'visualizar_candidaturas.html', {'vaga':vaga, 'candidaturas':candidaturas})

def custom_logout(request):
    logout(request) 
    return redirect('home')

candidaturas/templates/candidatar_vaga.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidatar</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'reset.css'%}">
    <link rel="stylesheet" href="{% static 'candidatar/candidatar.css' %}">
</head>
<body>
    <h2>Candidatar-se à Vaga: {{ vaga.nome }}</h2>
    <div class="descricao">
      <p>Requisitos - {{vaga.requisitos}}</p>
      <br>
      <p>Escolaridade mínima - {{vaga.get_escolaridade_minima_display}}</p>
    </div>
    <div>
      <form name="form" action="{% url 'candidatar_vaga' vaga.id %}" method="POST">
        {% csrf_token %}
        <div>
          <label for="experiencia">Experiência</label>
          {{ form.experiencia }}
        </div>
        <div>
          <label for="faixa_salarial">Pretensão Salarial</label>
          {{ form.pretensao_salarial }}
        </div>
        <div>
          <label for="escolaridade">Última escolaridade</label>
          {{ form.escolaridade }}
        </div>      
        <button type="submit">Enviar Candidatura</button>
        <a href="{% url 'listar_vagas_candidato' %}">Voltar para a lista de vagas</a>
      </form>
    </div>
</body>
<footer>
  <p>Sistema desenvolvido por Victor Soares para o Case Técnico da Job Convo</p>
</footer>
</html>

candidaturas/templates/listar_vagas_candidato.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'reset.css'%}">
  <link rel="stylesheet" href="{% static 'vagas/listar_vagas.css' %}">
</head>
<body>
  <h2 class="titulo">Vagas Disponíveis</h2>
  <br>
  <a href="{% url 'logout' %}" >Logout</a>
  <br><br><br>
  {% if messages %}  
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <ul>
    {% for vaga in vagas %}
      <li class="card_vaga">
        <h2 class="titulo_vaga">{{ vaga.nome }}</h2> 
        <br>
        <p class="escolaridade">Escolaridade mínima - {{vaga.get_escolaridade_minima_display}}</p>
        <br>
        <a class="botao-candidatar" href="{% url 'candidatar_vaga' vaga.id %}">Candidatar-se</a>
      </li>
    {% endfor %}
    
  </ul>
</body>
<footer>
  <p>Sistema desenvolvido por Victor Soares para o Case Técnico da Job Convo</p>
</footer>
</html>

candidaturas/templates/visualizar_candidaturas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar Vaga</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'vagas/visualizar_candidaturas.css' %}">
</head>
<body>
    <h2>Candidaturas para "{{ vaga.nome }}"</h2>
    <p>Requisitos - {{vaga.requisitos}}</p>
    <p>Faixa salarial - {{vaga.get_faixa_salarial_display}}</p>
    <p>Escolaridade mínima - {{vaga.get_escolaridade_minima_display}}</p>
    <table>
      <thead>
        <tr>
          <th>Candidato</th>
          <th>Email</th>
          <th>Pretensão Salarial</th>
          <th>Experiência</th>
          <th>Última Escolaridade</th>
          <th>Pontuação do Candidato</th>
        </tr>
      </thead>
      <tbody>
        {% for candidatura in candidaturas %}
          <tr>
            <td>{{ candidatura.candidato.first_name }}</td>
            <td>{{ candidatura.candidato.username }}</td>
            <td>{{ candidatura.pretensao_salarial }}</td>
            <td>{{ candidatura.experiencia }}</td>
            <td>{{ candidatura.escolaridade }}</td>
            <td>{{ candidatura.calcular_pontuacao}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'listar_vagas_adm' %}">Voltar para a lista de vagas</a>
</body>
<footer>
  <p>Sistema desenvolvido por Victor Soares para o Case Técnico da Job Convo</p>
</footer>
</html>